### ISSUE TITLE
SnSnVi | Direct switch to SnSnEd



### ISSUE THREAD

**Issue by KiwiKaiser** [SvenWollinger/SnipSniper#21]
Add the ability to switch directly to the editor again. Maybe even with an on-screen button.

**Comment by SvenWollinger** [comment]
I dont quite understand this, switch to the editor from what? 
You tagged it as both a bug and an enhancement, what is it? Both? If its a bug, how do you produce it?

**Comment by SvenWollinger** [comment]
Fixed in [3.0.1.20210516.1b](https://github.com/SvenWollinger/SnipSniper/releases/tag/3.0.1.20210516.1b).
Regarding on screen buttons, please create a seperate issue for that and if possible also attach images on how you want the on screen GUI to look, thank you!
