### ISSUE TITLE
SnSnVi | Rotation

### ISSUE THREAD

**Issue by KiwiKaiser** [SvenWollinger/SnipSniper#35]
Add 2 buttons to the top-bar to rotate the picture to the left/right

**Comment by KiwiKaiser** [comment]
Add third button to save the rotation status

**Comment by SvenWollinger** [comment]
Added in [this commit](https://github.com/SvenWollinger/SnipSniper/commit/2602c618d49768c94d68552d45461feb405dcef7).
I have only added one button, which rotates it clockwise 90 degrees every time pushed.
I thought this might make it faster to use, what do you think?
Saving already works though :)

**Comment by SvenWollinger** [comment]
I think this works as intended for now, write me a dm if you still want a second rotate button, thats not worth an issue atm imo.
