### ISSUE TITLE
Highlight-preview loses transparency

### ISSUE THREAD

**Issue by KiwiKaiser** [SvenWollinger/SnipSniper#4]
Highlight preview loses transparency when changing the color using the mouse wheel ("V" key) until you set the color manually using "C".
![2021-04-02T22_22_51_522_edited](https://user-images.githubusercontent.com/59627902/113451304-ff0f4100-9401-11eb-993d-5aaae8ee5275.png)

**Comment by SvenWollinger** [comment]
Fixed in [20210403_1](https://github.com/SvenWollinger/SnipSniper/releases/tag/20210403_1).
