### ISSUE TITLE
SnSnVi & SnSnEd | Open Explorer

### ISSUE THREAD

**Issue by KiwiKaiser** [SvenWollinger/SnipSniper#51]
When SnSnVi & SnSnEd is opened without a picture (Standard picture). Open file explorer on left-click to select a picture to view/edit.

**Comment by SvenWollinger** [comment]
Do we want it to do that when you are left & rightclicking or just one of the two?

**Comment by KiwiKaiser** [comment]
Due to our "right-click to close"-policy I would stick to this concept and
only apply the left-click. In case right-click does not already close
SnSnVi/SnSnEd in the "Start-Screen" we might add this there as well.

SvenWollinger ***@***.***> schrieb am Fr., 3. Sept. 2021,
07:27:

**Comment by SvenWollinger** [comment]
Great idea, will implement asap

**Comment by SvenWollinger** [comment]
Added for Editor and Viewer, re-open if anything is not working or you want to add something :)
